# Copyright (C) 2025 Ash Hellwig <ahellwig.dev@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: 🎆 Feature Request
description: Request a feature to be added unrelated to a bug or other issue.
title: "[Feature]: "
labels: ["enhancement", untriaged]
assignees:
  - ashellwig
body:
  - type: markdown
    attributes:
      value: |
        Request a feature to be added unrelated to a bug or other issue.
  - type: dropdown
    id: isbug
    attributes:
      label: Bug related?
      description: Is your feature request related to a problem?
      multiple: false
      options:
        - "Yes"
        - "No"
      default: 1
    validations:
      required: true
  - type: textarea
    id: feature-request
    attributes:
      label: What would you like to see?
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you see!
      value: A feature I would like to see added!
    validations:
      required: true
